# Cloudflare Pages configuration for Next.js app
name = "starter-nextjs-convex-ai"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

# This is a Pages project, not a Worker
pages_build_output_dir = "dist"

# Environment configurations
[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview] 
compatibility_flags = ["nodejs_compat"]